### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by jinman** [dukedhx/viewer-react-typescript-workbox#1]
Love the fact that it uses Reactv16 and HooksAPI. Any chance you have plain Javascript version of this?

**Comment by dukedhx** [comment]
https://github.com/Autodesk-Forge/viewer-nodejs-typeview.sample

**Comment by jinman** [comment]
Thanks @dukedhx. but these also seems to be typescript and older frameworks. 

Can you just point us to the official latest* React-based Javascript library for Forge Viewer that we can then try to convert it to use AWS Lambda/API Gateway instead of Express Server?

https://forge.autodesk.com/blog/running-forge-viewer-aws-lambda-server-and-api-gateway seems to be very old and does not use React
https://github.com/Autodesk-Forge/viewer-react-express-headless uses old version of React but does uses Express and 
https://github.com/dukedhx/viewer-react-typescript-workbox is great and latest (uses React and latest Hooks API) but uses typescript.

* React V16, React Router v5, MaterialUI v4, built with React Hooks and React Context (No Redux)

**Comment by dukedhx** [comment]
Then we’ve only got https://github.com/Autodesk-Forge/viewer-nodejs-typeview.sample for vanilla React 16 and Viewer.

If that’s still too bloated try our [Serverless/Claudia.js sample](https://forge.autodesk.com/blog/forge-viewer-faster-serverless-deployment-using-claudiajs)

Otherwise I’ve got plans to whip up a Serverless sample with more up to date dependencies and it’s due out early march.

**Comment by jinman** [comment]
I found Forge-RCDB https://github.com/Autodesk-Forge/forge-rcdb.nodejs but need something simpler to deploy using serverless framework (Lambda/API gateway) for 2LeggedAuth using React v16 and Hooks, preferably material-UI.
